export const suggestedSkills = [
  "Adaptability",
  "Agile Methodology",
  "Artificial Intelligence (AI)",
  "Blockchain",
  "Business Analysis",
  "Change Management",
  "Client Relations",
  "Cloud Computing",
  "Collaboration",
  "Communication",
  "Creativity",
  "Cross-functional Collaboration",
  "Customer Service",
  "Customer Success",
  "Data Analysis",
  "Data Analytics",
  "Data Science",
  "Digital Marketing",
  "Diversity, Equity, and Inclusion (DEI)",
  "Emotional Intelligence",
  "Human Resources",
  "Leadership",
  "Machine Learning",
  "Management",
  "Marketing Strategy",
  "Operations Management",
  "Persuasion",
  "Product Development",
  "Product Management",
  "Project Management",
  "Relationship Building",
  "Sales",
  "Software Development Lifecycles (SDLC)",
  "Software Engineering",
  "Stakeholder Management",
  "Strategic Planning",
  "Team Building",
  "Team Management",
  "UI/UX Design",
  "Video Production",
];
